version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    container_name: inventory-frontend
    restart: unless-stopped
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge